version: '3.8'

services:
  video-player:
    build: .
    container_name: video-player-app
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/app/videos
      - ./thumbnails:/app/thumbnails
      - ./logs:/app/logs
      - ./playlists.json:/app/playlists.json
      - ./favorites.json:/app/favorites.json
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/browse', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: video-player-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./videos:/usr/share/nginx/html/player/videos
      - ./thumbnails:/usr/share/nginx/html/player/thumbnails
      - ./public:/usr/share/nginx/html/player/public
    depends_on:
      - video-player
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/player/"]
      interval: 30s
      timeout: 10s
      retries: 3
